### ISSUE TITLE
Whatsapp beta updater changelog

### ISSUE THREAD

**Issue by Seranok** [javiersantos/WhatsAppBetaUpdater.Android#7]
Is there no way you can add changelog to your app. This app is gold but at the same time there is no changelog. So whats the point of beta updates. Thanks.

**Comment by javiersantos** [comment]
There is not an official changelog for beta updates, so it is not possible to implement this.

**Comment by Seranok** [comment]
Does whatsapp support this initiative?



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=ta&cv=7.2.9&pv=4.0.4] On Tue, Sep 01, 2015 at 1:15 AM, Javier Santos < notifications@github.com [notifications@github.com] > wrote:
There is not an official changelog for beta updates, so it is not possible to
implement this.

—
Reply to this email directly or view it on GitHub
[https://github.com/javiersantos/WhatsAppBetaUpdater.Android/issues/7#issuecomment-136515715] .[https://github.com/notifications/beacon/ANWXfag8BUkgLJ2OF-zmCXbHwgpiAbpeks5otMlzgaJpZM4F0oZk.gif]
